version: '3'
services:
  webserver:
    build: . # Dockerfileがあるディレクトリ
    container_name: nodeWeb
    tty: true
    privileged: true # root権限
    volumes:
      - ./app:/app
      - ../../../Data:/data #データディレクトリを接続
    ports:
      - "3001:80"
    command: /bin/sh -c "cd /app && npm install && npm start"
