version: '3'
services:
  webserver:
    build: . # Dockerfileがあるディレクトリ
    container_name: node
    tty: true
    privileged: true # root権限
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
      - "3001:3001"
