version: '3'
services:
  webserver:
    build: . # Dockerfileがあるディレクトリ
    container_name: node
    tty: true
    volumes:
      - ./app:/app
      - /app/node_modules #バインドフォルダを強制指定 http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
    ports:
      - "3000:3000"
