version: '3'
services:
  webserver:
    build: . # Dockerfileがあるディレクトリ
    container_name: node
    tty: true
    privileged: true # root権限
    volumes:
      - ./app:/app
      - ../../../Data:/data #データディレクトリを接続
    ports:
      - "80:80"
